// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkhikkvvpfjlvpvoxmgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBraGlra3Z2cGZqbHZwdm94bWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzc0ODEsImV4cCI6MjA3MzcxMzQ4MX0.Z35-A3L2hqv6HygHTbwgek3zfdv8Q0d0HUKeKnyj21Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});